# Generated by Django 2.1.1 on 2018-10-29 15:33

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='goods')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_deleted', models.BooleanField(default=False)),
                ('unit', models.CharField(default='500g', max_length=10)),
                ('click', models.IntegerField(default=0)),
                ('brief', models.CharField(max_length=120)),
                ('detail', tinymce.models.HTMLField()),
                ('in_stock', models.IntegerField()),
                ('is_promoted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory')),
            ],
        ),
    ]
