# Generated by Django 2.1.4 on 2018-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181221_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='in_stock',
            field=models.IntegerField(default=10),
        ),
    ]
